live_config_reload = true
shell = { program = "/opt/homebrew/bin/bash" }

[window]
option_as_alt = "OnlyLeft"

[font]
size = 14

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Italic"
